openapi: '3.0.2'
info:
  title: oogiri-bot
  version: '1.0'
servers:
  - url: https://api.oogiri-bot/v1
paths:
  /odai:
    post:
      tags: 
        - "odai"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - "title"
                - "createdBy"
              properties:
                title:
                  type: string
                  description: "お題の内容"
                  example: "こんなパン屋さんは嫌だ"
                createdBy:
                  type: string
                  description: "お題を作成したユーザーのSlackID"
                  example: "A123456"
      responses:
        '200':
          description: OK
  /odai/current:
    get:
      tags: 
        - "odai"
      responses:
        '200':
          description: OK
  /odai/start-voting:
    post:
      tags: 
        - "odai"
      responses:
        '200':
          description: OK
  /odai/finish:
    post:
      tags: 
        - "odai"
      responses:
        '200':
          description: OK
  /kotae:
    post:
      tags:
        - "kotae"
      responses:
        '200':
          description: OK
  /kotae/vote:
    post:
      tags:
        - "kotae"
      responses:
        '200':
          description: OK
