name: Deploy API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Firebase Functions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.19.5"

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install && cd packages/api && yarn install && yarn generate-schema

      - name: Deploy to Firebase Functions
        run: cd packages/api && yarn deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
